// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: common.proto

package apexpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_STATUS_UNKNOWN  Status = 0
	Status_STATUS_ACTIVE   Status = 1
	Status_STATUS_INACTIVE Status = 2
	Status_STATUS_ERROR    Status = 3
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "STATUS_UNKNOWN",
		1: "STATUS_ACTIVE",
		2: "STATUS_INACTIVE",
		3: "STATUS_ERROR",
	}
	Status_value = map[string]int32{
		"STATUS_UNKNOWN":  0,
		"STATUS_ACTIVE":   1,
		"STATUS_INACTIVE": 2,
		"STATUS_ERROR":    3,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

type OperatorRole int32

const (
	OperatorRole_OPERATOR_ROLE_UNKNOWN  OperatorRole = 0
	OperatorRole_OPERATOR_ROLE_ADMIN    OperatorRole = 1
	OperatorRole_OPERATOR_ROLE_OPERATOR OperatorRole = 2
	OperatorRole_OPERATOR_ROLE_READONLY OperatorRole = 3
)

// Enum value maps for OperatorRole.
var (
	OperatorRole_name = map[int32]string{
		0: "OPERATOR_ROLE_UNKNOWN",
		1: "OPERATOR_ROLE_ADMIN",
		2: "OPERATOR_ROLE_OPERATOR",
		3: "OPERATOR_ROLE_READONLY",
	}
	OperatorRole_value = map[string]int32{
		"OPERATOR_ROLE_UNKNOWN":  0,
		"OPERATOR_ROLE_ADMIN":    1,
		"OPERATOR_ROLE_OPERATOR": 2,
		"OPERATOR_ROLE_READONLY": 3,
	}
)

func (x OperatorRole) Enum() *OperatorRole {
	p := new(OperatorRole)
	*p = x
	return p
}

func (x OperatorRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OperatorRole) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[1].Descriptor()
}

func (OperatorRole) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[1]
}

func (x OperatorRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OperatorRole.Descriptor instead.
func (OperatorRole) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

type ListenerProtocol int32

const (
	ListenerProtocol_LISTENER_PROTOCOL_UNKNOWN ListenerProtocol = 0
	ListenerProtocol_LISTENER_PROTOCOL_HTTP    ListenerProtocol = 1
	ListenerProtocol_LISTENER_PROTOCOL_HTTPS   ListenerProtocol = 2
	ListenerProtocol_LISTENER_PROTOCOL_DNS     ListenerProtocol = 3
	ListenerProtocol_LISTENER_PROTOCOL_TCP     ListenerProtocol = 4
	ListenerProtocol_LISTENER_PROTOCOL_SMB     ListenerProtocol = 5
)

// Enum value maps for ListenerProtocol.
var (
	ListenerProtocol_name = map[int32]string{
		0: "LISTENER_PROTOCOL_UNKNOWN",
		1: "LISTENER_PROTOCOL_HTTP",
		2: "LISTENER_PROTOCOL_HTTPS",
		3: "LISTENER_PROTOCOL_DNS",
		4: "LISTENER_PROTOCOL_TCP",
		5: "LISTENER_PROTOCOL_SMB",
	}
	ListenerProtocol_value = map[string]int32{
		"LISTENER_PROTOCOL_UNKNOWN": 0,
		"LISTENER_PROTOCOL_HTTP":    1,
		"LISTENER_PROTOCOL_HTTPS":   2,
		"LISTENER_PROTOCOL_DNS":     3,
		"LISTENER_PROTOCOL_TCP":     4,
		"LISTENER_PROTOCOL_SMB":     5,
	}
)

func (x ListenerProtocol) Enum() *ListenerProtocol {
	p := new(ListenerProtocol)
	*p = x
	return p
}

func (x ListenerProtocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ListenerProtocol) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[2].Descriptor()
}

func (ListenerProtocol) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[2]
}

func (x ListenerProtocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ListenerProtocol.Descriptor instead.
func (ListenerProtocol) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{2}
}

type TaskStatus int32

const (
	TaskStatus_TASK_STATUS_UNKNOWN   TaskStatus = 0
	TaskStatus_TASK_STATUS_QUEUED    TaskStatus = 1
	TaskStatus_TASK_STATUS_DELIVERED TaskStatus = 2
	TaskStatus_TASK_STATUS_COMPLETED TaskStatus = 3
	TaskStatus_TASK_STATUS_FAILED    TaskStatus = 4
	TaskStatus_TASK_STATUS_CANCELLED TaskStatus = 5
)

// Enum value maps for TaskStatus.
var (
	TaskStatus_name = map[int32]string{
		0: "TASK_STATUS_UNKNOWN",
		1: "TASK_STATUS_QUEUED",
		2: "TASK_STATUS_DELIVERED",
		3: "TASK_STATUS_COMPLETED",
		4: "TASK_STATUS_FAILED",
		5: "TASK_STATUS_CANCELLED",
	}
	TaskStatus_value = map[string]int32{
		"TASK_STATUS_UNKNOWN":   0,
		"TASK_STATUS_QUEUED":    1,
		"TASK_STATUS_DELIVERED": 2,
		"TASK_STATUS_COMPLETED": 3,
		"TASK_STATUS_FAILED":    4,
		"TASK_STATUS_CANCELLED": 5,
	}
)

func (x TaskStatus) Enum() *TaskStatus {
	p := new(TaskStatus)
	*p = x
	return p
}

func (x TaskStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[3].Descriptor()
}

func (TaskStatus) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[3]
}

func (x TaskStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskStatus.Descriptor instead.
func (TaskStatus) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{3}
}

type Operator struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Role          OperatorRole           `protobuf:"varint,3,opt,name=role,proto3,enum=apex.OperatorRole" json:"role,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LastLogin     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=last_login,json=lastLogin,proto3" json:"last_login,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Operator) Reset() {
	*x = Operator{}
	mi := &file_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Operator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Operator) ProtoMessage() {}

func (x *Operator) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Operator.ProtoReflect.Descriptor instead.
func (*Operator) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

func (x *Operator) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Operator) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Operator) GetRole() OperatorRole {
	if x != nil {
		return x.Role
	}
	return OperatorRole_OPERATOR_ROLE_UNKNOWN
}

func (x *Operator) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Operator) GetLastLogin() *timestamppb.Timestamp {
	if x != nil {
		return x.LastLogin
	}
	return nil
}

type Listener struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Protocol      ListenerProtocol       `protobuf:"varint,3,opt,name=protocol,proto3,enum=apex.ListenerProtocol" json:"protocol,omitempty"`
	BindAddress   string                 `protobuf:"bytes,4,opt,name=bind_address,json=bindAddress,proto3" json:"bind_address,omitempty"`
	BindPort      int32                  `protobuf:"varint,5,opt,name=bind_port,json=bindPort,proto3" json:"bind_port,omitempty"`
	Status        Status                 `protobuf:"varint,6,opt,name=status,proto3,enum=apex.Status" json:"status,omitempty"`
	Config        map[string]string      `protobuf:"bytes,7,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Listener) Reset() {
	*x = Listener{}
	mi := &file_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Listener) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Listener) ProtoMessage() {}

func (x *Listener) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Listener.ProtoReflect.Descriptor instead.
func (*Listener) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

func (x *Listener) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Listener) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Listener) GetProtocol() ListenerProtocol {
	if x != nil {
		return x.Protocol
	}
	return ListenerProtocol_LISTENER_PROTOCOL_UNKNOWN
}

func (x *Listener) GetBindAddress() string {
	if x != nil {
		return x.BindAddress
	}
	return ""
}

func (x *Listener) GetBindPort() int32 {
	if x != nil {
		return x.BindPort
	}
	return 0
}

func (x *Listener) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNKNOWN
}

func (x *Listener) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *Listener) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type Agent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Os            string                 `protobuf:"bytes,4,opt,name=os,proto3" json:"os,omitempty"`
	Arch          string                 `protobuf:"bytes,5,opt,name=arch,proto3" json:"arch,omitempty"`
	Pid           int32                  `protobuf:"varint,6,opt,name=pid,proto3" json:"pid,omitempty"`
	ProcessName   string                 `protobuf:"bytes,7,opt,name=process_name,json=processName,proto3" json:"process_name,omitempty"`
	InternalIp    string                 `protobuf:"bytes,8,opt,name=internal_ip,json=internalIp,proto3" json:"internal_ip,omitempty"`
	ExternalIp    string                 `protobuf:"bytes,9,opt,name=external_ip,json=externalIp,proto3" json:"external_ip,omitempty"`
	Sleep         int32                  `protobuf:"varint,10,opt,name=sleep,proto3" json:"sleep,omitempty"`
	Jitter        int32                  `protobuf:"varint,11,opt,name=jitter,proto3" json:"jitter,omitempty"`
	ListenerId    string                 `protobuf:"bytes,12,opt,name=listener_id,json=listenerId,proto3" json:"listener_id,omitempty"`
	FirstSeen     *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=first_seen,json=firstSeen,proto3" json:"first_seen,omitempty"`
	LastSeen      *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	Status        Status                 `protobuf:"varint,15,opt,name=status,proto3,enum=apex.Status" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Agent) Reset() {
	*x = Agent{}
	mi := &file_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Agent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Agent) ProtoMessage() {}

func (x *Agent) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Agent.ProtoReflect.Descriptor instead.
func (*Agent) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{2}
}

func (x *Agent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Agent) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *Agent) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Agent) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *Agent) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *Agent) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *Agent) GetProcessName() string {
	if x != nil {
		return x.ProcessName
	}
	return ""
}

func (x *Agent) GetInternalIp() string {
	if x != nil {
		return x.InternalIp
	}
	return ""
}

func (x *Agent) GetExternalIp() string {
	if x != nil {
		return x.ExternalIp
	}
	return ""
}

func (x *Agent) GetSleep() int32 {
	if x != nil {
		return x.Sleep
	}
	return 0
}

func (x *Agent) GetJitter() int32 {
	if x != nil {
		return x.Jitter
	}
	return 0
}

func (x *Agent) GetListenerId() string {
	if x != nil {
		return x.ListenerId
	}
	return ""
}

func (x *Agent) GetFirstSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.FirstSeen
	}
	return nil
}

func (x *Agent) GetLastSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeen
	}
	return nil
}

func (x *Agent) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNKNOWN
}

type Task struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AgentId       string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	OperatorId    string                 `protobuf:"bytes,3,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"`
	Command       string                 `protobuf:"bytes,4,opt,name=command,proto3" json:"command,omitempty"`
	Arguments     []byte                 `protobuf:"bytes,5,opt,name=arguments,proto3" json:"arguments,omitempty"`
	Status        TaskStatus             `protobuf:"varint,6,opt,name=status,proto3,enum=apex.TaskStatus" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	CompletedAt   *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{3}
}

func (x *Task) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Task) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *Task) GetOperatorId() string {
	if x != nil {
		return x.OperatorId
	}
	return ""
}

func (x *Task) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *Task) GetArguments() []byte {
	if x != nil {
		return x.Arguments
	}
	return nil
}

func (x *Task) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_TASK_STATUS_UNKNOWN
}

func (x *Task) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Task) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

type TaskResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	AgentId       string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Output        []byte                 `protobuf:"bytes,3,opt,name=output,proto3" json:"output,omitempty"`
	Success       bool                   `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResult) Reset() {
	*x = TaskResult{}
	mi := &file_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResult) ProtoMessage() {}

func (x *TaskResult) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResult.ProtoReflect.Descriptor instead.
func (*TaskResult) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{4}
}

func (x *TaskResult) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskResult) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *TaskResult) GetOutput() []byte {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *TaskResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TaskResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *TaskResult) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_common_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{5}
}

var File_common_proto protoreflect.FileDescriptor

const file_common_proto_rawDesc = "" +
	"\n" +
	"\fcommon.proto\x12\x04apex\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd4\x01\n" +
	"\bOperator\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12&\n" +
	"\x04role\x18\x03 \x01(\x0e2\x12.apex.OperatorRoleR\x04role\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"last_login\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tlastLogin\"\xf2\x02\n" +
	"\bListener\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x122\n" +
	"\bprotocol\x18\x03 \x01(\x0e2\x16.apex.ListenerProtocolR\bprotocol\x12!\n" +
	"\fbind_address\x18\x04 \x01(\tR\vbindAddress\x12\x1b\n" +
	"\tbind_port\x18\x05 \x01(\x05R\bbindPort\x12$\n" +
	"\x06status\x18\x06 \x01(\x0e2\f.apex.StatusR\x06status\x122\n" +
	"\x06config\x18\a \x03(\v2\x1a.apex.Listener.ConfigEntryR\x06config\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd3\x03\n" +
	"\x05Agent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x0e\n" +
	"\x02os\x18\x04 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\x05 \x01(\tR\x04arch\x12\x10\n" +
	"\x03pid\x18\x06 \x01(\x05R\x03pid\x12!\n" +
	"\fprocess_name\x18\a \x01(\tR\vprocessName\x12\x1f\n" +
	"\vinternal_ip\x18\b \x01(\tR\n" +
	"internalIp\x12\x1f\n" +
	"\vexternal_ip\x18\t \x01(\tR\n" +
	"externalIp\x12\x14\n" +
	"\x05sleep\x18\n" +
	" \x01(\x05R\x05sleep\x12\x16\n" +
	"\x06jitter\x18\v \x01(\x05R\x06jitter\x12\x1f\n" +
	"\vlistener_id\x18\f \x01(\tR\n" +
	"listenerId\x129\n" +
	"\n" +
	"first_seen\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tfirstSeen\x127\n" +
	"\tlast_seen\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\blastSeen\x12$\n" +
	"\x06status\x18\x0f \x01(\x0e2\f.apex.StatusR\x06status\"\xae\x02\n" +
	"\x04Task\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12\x1f\n" +
	"\voperator_id\x18\x03 \x01(\tR\n" +
	"operatorId\x12\x18\n" +
	"\acommand\x18\x04 \x01(\tR\acommand\x12\x1c\n" +
	"\targuments\x18\x05 \x01(\fR\targuments\x12(\n" +
	"\x06status\x18\x06 \x01(\x0e2\x10.apex.TaskStatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12=\n" +
	"\fcompleted_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\"\xc2\x01\n" +
	"\n" +
	"TaskResult\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12\x16\n" +
	"\x06output\x18\x03 \x01(\fR\x06output\x12\x18\n" +
	"\asuccess\x18\x04 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\x128\n" +
	"\ttimestamp\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\a\n" +
	"\x05Empty*V\n" +
	"\x06Status\x12\x12\n" +
	"\x0eSTATUS_UNKNOWN\x10\x00\x12\x11\n" +
	"\rSTATUS_ACTIVE\x10\x01\x12\x13\n" +
	"\x0fSTATUS_INACTIVE\x10\x02\x12\x10\n" +
	"\fSTATUS_ERROR\x10\x03*z\n" +
	"\fOperatorRole\x12\x19\n" +
	"\x15OPERATOR_ROLE_UNKNOWN\x10\x00\x12\x17\n" +
	"\x13OPERATOR_ROLE_ADMIN\x10\x01\x12\x1a\n" +
	"\x16OPERATOR_ROLE_OPERATOR\x10\x02\x12\x1a\n" +
	"\x16OPERATOR_ROLE_READONLY\x10\x03*\xbb\x01\n" +
	"\x10ListenerProtocol\x12\x1d\n" +
	"\x19LISTENER_PROTOCOL_UNKNOWN\x10\x00\x12\x1a\n" +
	"\x16LISTENER_PROTOCOL_HTTP\x10\x01\x12\x1b\n" +
	"\x17LISTENER_PROTOCOL_HTTPS\x10\x02\x12\x19\n" +
	"\x15LISTENER_PROTOCOL_DNS\x10\x03\x12\x19\n" +
	"\x15LISTENER_PROTOCOL_TCP\x10\x04\x12\x19\n" +
	"\x15LISTENER_PROTOCOL_SMB\x10\x05*\xa6\x01\n" +
	"\n" +
	"TaskStatus\x12\x17\n" +
	"\x13TASK_STATUS_UNKNOWN\x10\x00\x12\x16\n" +
	"\x12TASK_STATUS_QUEUED\x10\x01\x12\x19\n" +
	"\x15TASK_STATUS_DELIVERED\x10\x02\x12\x19\n" +
	"\x15TASK_STATUS_COMPLETED\x10\x03\x12\x16\n" +
	"\x12TASK_STATUS_FAILED\x10\x04\x12\x19\n" +
	"\x15TASK_STATUS_CANCELLED\x10\x05B\"Z apex/teamserver/pkg/proto/apexpbb\x06proto3"

var (
	file_common_proto_rawDescOnce sync.Once
	file_common_proto_rawDescData []byte
)

func file_common_proto_rawDescGZIP() []byte {
	file_common_proto_rawDescOnce.Do(func() {
		file_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)))
	})
	return file_common_proto_rawDescData
}

var file_common_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_common_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_common_proto_goTypes = []any{
	(Status)(0),                   // 0: apex.Status
	(OperatorRole)(0),             // 1: apex.OperatorRole
	(ListenerProtocol)(0),         // 2: apex.ListenerProtocol
	(TaskStatus)(0),               // 3: apex.TaskStatus
	(*Operator)(nil),              // 4: apex.Operator
	(*Listener)(nil),              // 5: apex.Listener
	(*Agent)(nil),                 // 6: apex.Agent
	(*Task)(nil),                  // 7: apex.Task
	(*TaskResult)(nil),            // 8: apex.TaskResult
	(*Empty)(nil),                 // 9: apex.Empty
	nil,                           // 10: apex.Listener.ConfigEntry
	(*timestamppb.Timestamp)(nil), // 11: google.protobuf.Timestamp
}
var file_common_proto_depIdxs = []int32{
	1,  // 0: apex.Operator.role:type_name -> apex.OperatorRole
	11, // 1: apex.Operator.created_at:type_name -> google.protobuf.Timestamp
	11, // 2: apex.Operator.last_login:type_name -> google.protobuf.Timestamp
	2,  // 3: apex.Listener.protocol:type_name -> apex.ListenerProtocol
	0,  // 4: apex.Listener.status:type_name -> apex.Status
	10, // 5: apex.Listener.config:type_name -> apex.Listener.ConfigEntry
	11, // 6: apex.Listener.created_at:type_name -> google.protobuf.Timestamp
	11, // 7: apex.Agent.first_seen:type_name -> google.protobuf.Timestamp
	11, // 8: apex.Agent.last_seen:type_name -> google.protobuf.Timestamp
	0,  // 9: apex.Agent.status:type_name -> apex.Status
	3,  // 10: apex.Task.status:type_name -> apex.TaskStatus
	11, // 11: apex.Task.created_at:type_name -> google.protobuf.Timestamp
	11, // 12: apex.Task.completed_at:type_name -> google.protobuf.Timestamp
	11, // 13: apex.TaskResult.timestamp:type_name -> google.protobuf.Timestamp
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_common_proto_init() }
func file_common_proto_init() {
	if File_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_proto_goTypes,
		DependencyIndexes: file_common_proto_depIdxs,
		EnumInfos:         file_common_proto_enumTypes,
		MessageInfos:      file_common_proto_msgTypes,
	}.Build()
	File_common_proto = out.File
	file_common_proto_goTypes = nil
	file_common_proto_depIdxs = nil
}
