// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: listeners.proto

package apexpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateListenerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Protocol      ListenerProtocol       `protobuf:"varint,2,opt,name=protocol,proto3,enum=apex.ListenerProtocol" json:"protocol,omitempty"`
	BindAddress   string                 `protobuf:"bytes,3,opt,name=bind_address,json=bindAddress,proto3" json:"bind_address,omitempty"`
	BindPort      int32                  `protobuf:"varint,4,opt,name=bind_port,json=bindPort,proto3" json:"bind_port,omitempty"`
	Config        map[string]string      `protobuf:"bytes,5,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateListenerRequest) Reset() {
	*x = CreateListenerRequest{}
	mi := &file_listeners_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateListenerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateListenerRequest) ProtoMessage() {}

func (x *CreateListenerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_listeners_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateListenerRequest.ProtoReflect.Descriptor instead.
func (*CreateListenerRequest) Descriptor() ([]byte, []int) {
	return file_listeners_proto_rawDescGZIP(), []int{0}
}

func (x *CreateListenerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateListenerRequest) GetProtocol() ListenerProtocol {
	if x != nil {
		return x.Protocol
	}
	return ListenerProtocol_LISTENER_PROTOCOL_UNKNOWN
}

func (x *CreateListenerRequest) GetBindAddress() string {
	if x != nil {
		return x.BindAddress
	}
	return ""
}

func (x *CreateListenerRequest) GetBindPort() int32 {
	if x != nil {
		return x.BindPort
	}
	return 0
}

func (x *CreateListenerRequest) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

type GetListenerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetListenerRequest) Reset() {
	*x = GetListenerRequest{}
	mi := &file_listeners_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListenerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListenerRequest) ProtoMessage() {}

func (x *GetListenerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_listeners_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListenerRequest.ProtoReflect.Descriptor instead.
func (*GetListenerRequest) Descriptor() ([]byte, []int) {
	return file_listeners_proto_rawDescGZIP(), []int{1}
}

func (x *GetListenerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListListenersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Listeners     []*Listener            `protobuf:"bytes,1,rep,name=listeners,proto3" json:"listeners,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListListenersResponse) Reset() {
	*x = ListListenersResponse{}
	mi := &file_listeners_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListListenersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListListenersResponse) ProtoMessage() {}

func (x *ListListenersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_listeners_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListListenersResponse.ProtoReflect.Descriptor instead.
func (*ListListenersResponse) Descriptor() ([]byte, []int) {
	return file_listeners_proto_rawDescGZIP(), []int{2}
}

func (x *ListListenersResponse) GetListeners() []*Listener {
	if x != nil {
		return x.Listeners
	}
	return nil
}

type StartListenerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartListenerRequest) Reset() {
	*x = StartListenerRequest{}
	mi := &file_listeners_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartListenerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartListenerRequest) ProtoMessage() {}

func (x *StartListenerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_listeners_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartListenerRequest.ProtoReflect.Descriptor instead.
func (*StartListenerRequest) Descriptor() ([]byte, []int) {
	return file_listeners_proto_rawDescGZIP(), []int{3}
}

func (x *StartListenerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type StopListenerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopListenerRequest) Reset() {
	*x = StopListenerRequest{}
	mi := &file_listeners_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopListenerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopListenerRequest) ProtoMessage() {}

func (x *StopListenerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_listeners_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopListenerRequest.ProtoReflect.Descriptor instead.
func (*StopListenerRequest) Descriptor() ([]byte, []int) {
	return file_listeners_proto_rawDescGZIP(), []int{4}
}

func (x *StopListenerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteListenerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteListenerRequest) Reset() {
	*x = DeleteListenerRequest{}
	mi := &file_listeners_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteListenerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteListenerRequest) ProtoMessage() {}

func (x *DeleteListenerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_listeners_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteListenerRequest.ProtoReflect.Descriptor instead.
func (*DeleteListenerRequest) Descriptor() ([]byte, []int) {
	return file_listeners_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteListenerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListenerEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ListenerId    string                 `protobuf:"bytes,1,opt,name=listener_id,json=listenerId,proto3" json:"listener_id,omitempty"`
	EventType     string                 `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"` // "started", "stopped", "error", "agent_checkin"
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Listener      *Listener              `protobuf:"bytes,4,opt,name=listener,proto3" json:"listener,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListenerEvent) Reset() {
	*x = ListenerEvent{}
	mi := &file_listeners_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListenerEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListenerEvent) ProtoMessage() {}

func (x *ListenerEvent) ProtoReflect() protoreflect.Message {
	mi := &file_listeners_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListenerEvent.ProtoReflect.Descriptor instead.
func (*ListenerEvent) Descriptor() ([]byte, []int) {
	return file_listeners_proto_rawDescGZIP(), []int{6}
}

func (x *ListenerEvent) GetListenerId() string {
	if x != nil {
		return x.ListenerId
	}
	return ""
}

func (x *ListenerEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *ListenerEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ListenerEvent) GetListener() *Listener {
	if x != nil {
		return x.Listener
	}
	return nil
}

var File_listeners_proto protoreflect.FileDescriptor

const file_listeners_proto_rawDesc = "" +
	"\n" +
	"\x0flisteners.proto\x12\x04apex\x1a\fcommon.proto\"\x9b\x02\n" +
	"\x15CreateListenerRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x122\n" +
	"\bprotocol\x18\x02 \x01(\x0e2\x16.apex.ListenerProtocolR\bprotocol\x12!\n" +
	"\fbind_address\x18\x03 \x01(\tR\vbindAddress\x12\x1b\n" +
	"\tbind_port\x18\x04 \x01(\x05R\bbindPort\x12?\n" +
	"\x06config\x18\x05 \x03(\v2'.apex.CreateListenerRequest.ConfigEntryR\x06config\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"$\n" +
	"\x12GetListenerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"E\n" +
	"\x15ListListenersResponse\x12,\n" +
	"\tlisteners\x18\x01 \x03(\v2\x0e.apex.ListenerR\tlisteners\"&\n" +
	"\x14StartListenerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"%\n" +
	"\x13StopListenerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"'\n" +
	"\x15DeleteListenerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x95\x01\n" +
	"\rListenerEvent\x12\x1f\n" +
	"\vlistener_id\x18\x01 \x01(\tR\n" +
	"listenerId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12*\n" +
	"\blistener\x18\x04 \x01(\v2\x0e.apex.ListenerR\blistener2\xb4\x03\n" +
	"\x0fListenerService\x12=\n" +
	"\x0eCreateListener\x12\x1b.apex.CreateListenerRequest\x1a\x0e.apex.Listener\x127\n" +
	"\vGetListener\x12\x18.apex.GetListenerRequest\x1a\x0e.apex.Listener\x129\n" +
	"\rListListeners\x12\v.apex.Empty\x1a\x1b.apex.ListListenersResponse\x12;\n" +
	"\rStartListener\x12\x1a.apex.StartListenerRequest\x1a\x0e.apex.Listener\x129\n" +
	"\fStopListener\x12\x19.apex.StopListenerRequest\x1a\x0e.apex.Listener\x12:\n" +
	"\x0eDeleteListener\x12\x1b.apex.DeleteListenerRequest\x1a\v.apex.Empty\x12:\n" +
	"\x14StreamListenerEvents\x12\v.apex.Empty\x1a\x13.apex.ListenerEvent0\x01B\"Z apex/teamserver/pkg/proto/apexpbb\x06proto3"

var (
	file_listeners_proto_rawDescOnce sync.Once
	file_listeners_proto_rawDescData []byte
)

func file_listeners_proto_rawDescGZIP() []byte {
	file_listeners_proto_rawDescOnce.Do(func() {
		file_listeners_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_listeners_proto_rawDesc), len(file_listeners_proto_rawDesc)))
	})
	return file_listeners_proto_rawDescData
}

var file_listeners_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_listeners_proto_goTypes = []any{
	(*CreateListenerRequest)(nil), // 0: apex.CreateListenerRequest
	(*GetListenerRequest)(nil),    // 1: apex.GetListenerRequest
	(*ListListenersResponse)(nil), // 2: apex.ListListenersResponse
	(*StartListenerRequest)(nil),  // 3: apex.StartListenerRequest
	(*StopListenerRequest)(nil),   // 4: apex.StopListenerRequest
	(*DeleteListenerRequest)(nil), // 5: apex.DeleteListenerRequest
	(*ListenerEvent)(nil),         // 6: apex.ListenerEvent
	nil,                           // 7: apex.CreateListenerRequest.ConfigEntry
	(ListenerProtocol)(0),         // 8: apex.ListenerProtocol
	(*Listener)(nil),              // 9: apex.Listener
	(*Empty)(nil),                 // 10: apex.Empty
}
var file_listeners_proto_depIdxs = []int32{
	8,  // 0: apex.CreateListenerRequest.protocol:type_name -> apex.ListenerProtocol
	7,  // 1: apex.CreateListenerRequest.config:type_name -> apex.CreateListenerRequest.ConfigEntry
	9,  // 2: apex.ListListenersResponse.listeners:type_name -> apex.Listener
	9,  // 3: apex.ListenerEvent.listener:type_name -> apex.Listener
	0,  // 4: apex.ListenerService.CreateListener:input_type -> apex.CreateListenerRequest
	1,  // 5: apex.ListenerService.GetListener:input_type -> apex.GetListenerRequest
	10, // 6: apex.ListenerService.ListListeners:input_type -> apex.Empty
	3,  // 7: apex.ListenerService.StartListener:input_type -> apex.StartListenerRequest
	4,  // 8: apex.ListenerService.StopListener:input_type -> apex.StopListenerRequest
	5,  // 9: apex.ListenerService.DeleteListener:input_type -> apex.DeleteListenerRequest
	10, // 10: apex.ListenerService.StreamListenerEvents:input_type -> apex.Empty
	9,  // 11: apex.ListenerService.CreateListener:output_type -> apex.Listener
	9,  // 12: apex.ListenerService.GetListener:output_type -> apex.Listener
	2,  // 13: apex.ListenerService.ListListeners:output_type -> apex.ListListenersResponse
	9,  // 14: apex.ListenerService.StartListener:output_type -> apex.Listener
	9,  // 15: apex.ListenerService.StopListener:output_type -> apex.Listener
	10, // 16: apex.ListenerService.DeleteListener:output_type -> apex.Empty
	6,  // 17: apex.ListenerService.StreamListenerEvents:output_type -> apex.ListenerEvent
	11, // [11:18] is the sub-list for method output_type
	4,  // [4:11] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_listeners_proto_init() }
func file_listeners_proto_init() {
	if File_listeners_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_listeners_proto_rawDesc), len(file_listeners_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_listeners_proto_goTypes,
		DependencyIndexes: file_listeners_proto_depIdxs,
		MessageInfos:      file_listeners_proto_msgTypes,
	}.Build()
	File_listeners_proto = out.File
	file_listeners_proto_goTypes = nil
	file_listeners_proto_depIdxs = nil
}
