// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: listeners.proto

package apexpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ListenerService_CreateListener_FullMethodName       = "/apex.ListenerService/CreateListener"
	ListenerService_GetListener_FullMethodName          = "/apex.ListenerService/GetListener"
	ListenerService_ListListeners_FullMethodName        = "/apex.ListenerService/ListListeners"
	ListenerService_StartListener_FullMethodName        = "/apex.ListenerService/StartListener"
	ListenerService_StopListener_FullMethodName         = "/apex.ListenerService/StopListener"
	ListenerService_DeleteListener_FullMethodName       = "/apex.ListenerService/DeleteListener"
	ListenerService_StreamListenerEvents_FullMethodName = "/apex.ListenerService/StreamListenerEvents"
)

// ListenerServiceClient is the client API for ListenerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ListenerServiceClient interface {
	CreateListener(ctx context.Context, in *CreateListenerRequest, opts ...grpc.CallOption) (*Listener, error)
	GetListener(ctx context.Context, in *GetListenerRequest, opts ...grpc.CallOption) (*Listener, error)
	ListListeners(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListListenersResponse, error)
	StartListener(ctx context.Context, in *StartListenerRequest, opts ...grpc.CallOption) (*Listener, error)
	StopListener(ctx context.Context, in *StopListenerRequest, opts ...grpc.CallOption) (*Listener, error)
	DeleteListener(ctx context.Context, in *DeleteListenerRequest, opts ...grpc.CallOption) (*Empty, error)
	// Real-time listener status events
	StreamListenerEvents(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ListenerEvent], error)
}

type listenerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewListenerServiceClient(cc grpc.ClientConnInterface) ListenerServiceClient {
	return &listenerServiceClient{cc}
}

func (c *listenerServiceClient) CreateListener(ctx context.Context, in *CreateListenerRequest, opts ...grpc.CallOption) (*Listener, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Listener)
	err := c.cc.Invoke(ctx, ListenerService_CreateListener_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *listenerServiceClient) GetListener(ctx context.Context, in *GetListenerRequest, opts ...grpc.CallOption) (*Listener, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Listener)
	err := c.cc.Invoke(ctx, ListenerService_GetListener_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *listenerServiceClient) ListListeners(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListListenersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListListenersResponse)
	err := c.cc.Invoke(ctx, ListenerService_ListListeners_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *listenerServiceClient) StartListener(ctx context.Context, in *StartListenerRequest, opts ...grpc.CallOption) (*Listener, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Listener)
	err := c.cc.Invoke(ctx, ListenerService_StartListener_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *listenerServiceClient) StopListener(ctx context.Context, in *StopListenerRequest, opts ...grpc.CallOption) (*Listener, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Listener)
	err := c.cc.Invoke(ctx, ListenerService_StopListener_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *listenerServiceClient) DeleteListener(ctx context.Context, in *DeleteListenerRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ListenerService_DeleteListener_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *listenerServiceClient) StreamListenerEvents(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ListenerEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ListenerService_ServiceDesc.Streams[0], ListenerService_StreamListenerEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Empty, ListenerEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ListenerService_StreamListenerEventsClient = grpc.ServerStreamingClient[ListenerEvent]

// ListenerServiceServer is the server API for ListenerService service.
// All implementations must embed UnimplementedListenerServiceServer
// for forward compatibility.
type ListenerServiceServer interface {
	CreateListener(context.Context, *CreateListenerRequest) (*Listener, error)
	GetListener(context.Context, *GetListenerRequest) (*Listener, error)
	ListListeners(context.Context, *Empty) (*ListListenersResponse, error)
	StartListener(context.Context, *StartListenerRequest) (*Listener, error)
	StopListener(context.Context, *StopListenerRequest) (*Listener, error)
	DeleteListener(context.Context, *DeleteListenerRequest) (*Empty, error)
	// Real-time listener status events
	StreamListenerEvents(*Empty, grpc.ServerStreamingServer[ListenerEvent]) error
	mustEmbedUnimplementedListenerServiceServer()
}

// UnimplementedListenerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedListenerServiceServer struct{}

func (UnimplementedListenerServiceServer) CreateListener(context.Context, *CreateListenerRequest) (*Listener, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateListener not implemented")
}
func (UnimplementedListenerServiceServer) GetListener(context.Context, *GetListenerRequest) (*Listener, error) {
	return nil, status.Error(codes.Unimplemented, "method GetListener not implemented")
}
func (UnimplementedListenerServiceServer) ListListeners(context.Context, *Empty) (*ListListenersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListListeners not implemented")
}
func (UnimplementedListenerServiceServer) StartListener(context.Context, *StartListenerRequest) (*Listener, error) {
	return nil, status.Error(codes.Unimplemented, "method StartListener not implemented")
}
func (UnimplementedListenerServiceServer) StopListener(context.Context, *StopListenerRequest) (*Listener, error) {
	return nil, status.Error(codes.Unimplemented, "method StopListener not implemented")
}
func (UnimplementedListenerServiceServer) DeleteListener(context.Context, *DeleteListenerRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteListener not implemented")
}
func (UnimplementedListenerServiceServer) StreamListenerEvents(*Empty, grpc.ServerStreamingServer[ListenerEvent]) error {
	return status.Error(codes.Unimplemented, "method StreamListenerEvents not implemented")
}
func (UnimplementedListenerServiceServer) mustEmbedUnimplementedListenerServiceServer() {}
func (UnimplementedListenerServiceServer) testEmbeddedByValue()                         {}

// UnsafeListenerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ListenerServiceServer will
// result in compilation errors.
type UnsafeListenerServiceServer interface {
	mustEmbedUnimplementedListenerServiceServer()
}

func RegisterListenerServiceServer(s grpc.ServiceRegistrar, srv ListenerServiceServer) {
	// If the following call panics, it indicates UnimplementedListenerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ListenerService_ServiceDesc, srv)
}

func _ListenerService_CreateListener_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateListenerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ListenerServiceServer).CreateListener(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ListenerService_CreateListener_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ListenerServiceServer).CreateListener(ctx, req.(*CreateListenerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ListenerService_GetListener_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetListenerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ListenerServiceServer).GetListener(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ListenerService_GetListener_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ListenerServiceServer).GetListener(ctx, req.(*GetListenerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ListenerService_ListListeners_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ListenerServiceServer).ListListeners(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ListenerService_ListListeners_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ListenerServiceServer).ListListeners(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ListenerService_StartListener_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartListenerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ListenerServiceServer).StartListener(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ListenerService_StartListener_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ListenerServiceServer).StartListener(ctx, req.(*StartListenerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ListenerService_StopListener_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopListenerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ListenerServiceServer).StopListener(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ListenerService_StopListener_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ListenerServiceServer).StopListener(ctx, req.(*StopListenerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ListenerService_DeleteListener_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteListenerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ListenerServiceServer).DeleteListener(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ListenerService_DeleteListener_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ListenerServiceServer).DeleteListener(ctx, req.(*DeleteListenerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ListenerService_StreamListenerEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ListenerServiceServer).StreamListenerEvents(m, &grpc.GenericServerStream[Empty, ListenerEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ListenerService_StreamListenerEventsServer = grpc.ServerStreamingServer[ListenerEvent]

// ListenerService_ServiceDesc is the grpc.ServiceDesc for ListenerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ListenerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "apex.ListenerService",
	HandlerType: (*ListenerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateListener",
			Handler:    _ListenerService_CreateListener_Handler,
		},
		{
			MethodName: "GetListener",
			Handler:    _ListenerService_GetListener_Handler,
		},
		{
			MethodName: "ListListeners",
			Handler:    _ListenerService_ListListeners_Handler,
		},
		{
			MethodName: "StartListener",
			Handler:    _ListenerService_StartListener_Handler,
		},
		{
			MethodName: "StopListener",
			Handler:    _ListenerService_StopListener_Handler,
		},
		{
			MethodName: "DeleteListener",
			Handler:    _ListenerService_DeleteListener_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamListenerEvents",
			Handler:       _ListenerService_StreamListenerEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "listeners.proto",
}
